<h1>Table of Contents<span class="tocSkip"></span></h1>
<div class="toc"><ul class="toc-item"><li><span><a href="#Challenge-3" data-toc-modified-id="Challenge-3-1"><span class="toc-item-num">1&nbsp;&nbsp;</span>Challenge 3</a></span><ul class="toc-item"><li><span><a href="#Q1:-How-to-identify-VIP-&amp;-Preferred-Customers?" data-toc-modified-id="Q1:-How-to-identify-VIP-&amp;-Preferred-Customers?-1.1"><span class="toc-item-num">1.1&nbsp;&nbsp;</span>Q1: How to identify VIP &amp; Preferred Customers?</a></span></li><li><span><a href="#How-to-label-customers-whose-aggregated-amount_spent-is-in-a-given-quantile-range?" data-toc-modified-id="How-to-label-customers-whose-aggregated-amount_spent-is-in-a-given-quantile-range?-1.2"><span class="toc-item-num">1.2&nbsp;&nbsp;</span>How to label customers whose aggregated <code>amount_spent</code> is in a given quantile range?</a></span><ul class="toc-item"><li><ul class="toc-item"><li><span><a href="#Sub-Problem-1:-How-to-aggregate-the--amount_spent-for-unique-customers?" data-toc-modified-id="Sub-Problem-1:-How-to-aggregate-the--amount_spent-for-unique-customers?-1.2.0.1"><span class="toc-item-num">1.2.0.1&nbsp;&nbsp;</span>Sub Problem 1: How to aggregate the  <code>amount_spent</code> for unique customers?</a></span></li><li><span><a href="#Sub-Problem-2:-How-to-select-customers-whose-aggregated-amount_spent-is-in-a-given-quantile-range?" data-toc-modified-id="Sub-Problem-2:-How-to-select-customers-whose-aggregated-amount_spent-is-in-a-given-quantile-range?-1.2.0.2"><span class="toc-item-num">1.2.0.2&nbsp;&nbsp;</span>Sub Problem 2: How to select customers whose aggregated <code>amount_spent</code> is in a given quantile range?</a></span></li><li><span><a href="#Sub-Problem-3:-How-to-label-selected-customers-as-&quot;VIP&quot;-or-&quot;Preferred&quot;?" data-toc-modified-id="Sub-Problem-3:-How-to-label-selected-customers-as-&quot;VIP&quot;-or-&quot;Preferred&quot;?-1.2.0.3"><span class="toc-item-num">1.2.0.3&nbsp;&nbsp;</span>Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?</a></span></li></ul></li></ul></li><li><span><a href="#Q2:-How-to-identify-which-country-has-the-most-VIP-Customers?" data-toc-modified-id="Q2:-How-to-identify-which-country-has-the-most-VIP-Customers?-1.3"><span class="toc-item-num">1.3&nbsp;&nbsp;</span>Q2: How to identify which country has the most VIP Customers?</a></span></li><li><span><a href="#Q3:-How-to-identify-which-country-has-the-most-VIP+Preferred-Customers-combined?" data-toc-modified-id="Q3:-How-to-identify-which-country-has-the-most-VIP+Preferred-Customers-combined?-1.4"><span class="toc-item-num">1.4&nbsp;&nbsp;</span>Q3: How to identify which country has the most VIP+Preferred Customers combined?</a></span></li></ul></li></ul></div>

# Challenge 3

In this challenge we will work on the `Orders` data set (https://drive.google.com/file/d/1xUzMpyQgC5IaK61ehUH2C5P4jCPmLa-s/view?usp=sharing). In your work you will apply the thinking process and workflow we showed you in Challenge 2.

You are serving as a Data Analyst at the headquarter of an international fashion goods chain store. Your boss today asked you to do two things for her:

**First, identify two groups of customers from the data set.** The first group is **VIP Customers** whose **aggregated expenses** at your global chain stores are **above the 95th percentile** (aka. 0.95 quantile). The second group is **Preferred Customers** whose **aggregated expenses** are **between the 75th and 95th percentile**.

**Second, identify which country has the most of your VIP customers, and which country has the most of your VIP+Preferred Customers combined.**

## Q1: How to identify VIP & Preferred Customers?

We start by importing all the required libraries:

In [1]:
# import required libraries
import numpy as np
import pandas as pd

Next, import `Orders` from Ironhack's database into a dataframe variable called `orders`. Print the head of `orders` to overview the data:

In [4]:
# your code here

import io

from google.colab import files
uploaded = files.upload()

Saving Orders.csv to Orders.csv

In [6]:
import io
orders = pd.read_csv(io.BytesIO(uploaded['Orders.csv']))

orders

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent
0,0,536365,85123A,2010,12,3,8,white hanging heart t-light holder,6,2010-12-01 08:26:00,2.55,17850,United Kingdom,15.30
1,1,536365,71053,2010,12,3,8,white metal lantern,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
2,2,536365,84406B,2010,12,3,8,cream cupid hearts coat hanger,8,2010-12-01 08:26:00,2.75,17850,United Kingdom,22.00
3,3,536365,84029G,2010,12,3,8,knitted union flag hot water bottle,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
4,4,536365,84029E,2010,12,3,8,red woolly hottie white heart.,6,2010-12-01 08:26:00,3.39,17850,United Kingdom,20.34
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
397919,541904,581587,22613,2011,12,5,12,pack of 20 spaceboy napkins,12,2011-12-09 12:50:00,0.85,12680,France,10.20
397920,541905,581587,22899,2011,12,5,12,children's apron dolly girl,6,2011-12-09 12:50:00,2.10,12680,France,12.60
397921,541906,581587,23254,2011,12,5,12,childrens cutlery dolly girl,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397922,541907,581587,23255,2011,12,5,12,childrens cutlery circus parade,4,2011-12-09 12:50:00,4.15,12680,France,16.60
397923,541908,581587,22138,2011,12,5,12,baking set 9 piece retrospot,3,2011-12-09 12:50:00,4.95,12680,France,14.85

---

"Identify VIP and Preferred Customers" is the non-technical goal of your boss. You need to translate that goal into technical languages that data analysts use:

## How to label customers whose aggregated `amount_spent` is in a given quantile range?

We break down the main problem into several sub problems:

#### Sub Problem 1: How to aggregate the  `amount_spent` for unique customers?

#### Sub Problem 2: How to select customers whose aggregated `amount_spent` is in a given quantile range?

#### Sub Problem 3: How to label selected customers as "VIP" or "Preferred"?

*Note: If you want to break down the main problem in a different way, please feel free to revise the sub problems above.*

Now in the workspace below, tackle each of the sub problems using the iterative problem solving workflow. Insert cells as necessary to write your codes and explain your steps.

In [7]:
# your code here

agg_custom = orders.groupby("CustomerID").sum()[['amount_spent']]

In [8]:
agg_custom.head()

            amount_spent
CustomerID
12346           77183.60
12347            4310.00
12348            1797.24
12349            1757.55
12350             334.40

In [9]:
agg_custom.describe()

        amount_spent
count    4339.000000
mean     2053.793018
std      8988.248381
min         0.000000
25%       307.245000
50%       674.450000
75%      1661.640000
max    280206.020000

In [10]:
vip_list = agg_custom[agg_custom['amount_spent'] >= np.quantile(agg_custom['amount_spent'], 0.95)]

In [11]:
vip_list[:20]

            amount_spent
CustomerID
12346           77183.60
12357            6207.67
12359            6372.58
12409           11072.67
12415          124914.53
12428            7956.46
12431            6487.45
12433           13375.87
12435            7829.89
12451            9035.52
12471           19824.05
12472            6572.11
12474            7375.79
12476            6816.42
12477           13219.74
12536           12601.83
12540           13400.24
12557           11990.96
12567            9401.28
12583            7281.38

In [12]:
orders["VIP"] = np.where(orders["CustomerID"].isin(vip_list.index), 1, 0)
orders.sample(20)

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,VIP
200033,285986,561969,22690,2011,8,1,13,doormat home sweet home blue,1,2011-08-01 13:31:00,7.95,17757,United Kingdom,7.95,0
84052,127323,547209,22423,2011,3,1,14,regency cakestand 3 tier,16,2011-03-21 14:44:00,10.95,13081,United Kingdom,175.20,1
212862,302661,563441,23093,2011,8,2,13,small parisienne heart photo frame,4,2011-08-16 13:13:00,2.49,13140,United Kingdom,9.96,0
206726,294171,562688,22565,2011,8,1,13,feltcraft hairbands pink and white,4,2011-08-08 13:53:00,0.85,13869,United Kingdom,3.40,0
353588,480060,577252,85035C,2011,11,5,12,rose 3 wick morris box candle,2,2011-11-18 12:22:00,1.25,18034,United Kingdom,2.50,0
159049,227582,556883,22960,2011,6,3,12,jam making set with jars,6,2011-06-15 12:24:00,4.25,13343,United Kingdom,25.50,0
382578,519103,580136,22749,2011,12,4,19,feltcraft princess charlotte doll,1,2011-12-01 19:42:00,3.75,17841,United Kingdom,3.75,1
391968,531596,580956,22989,2011,12,2,14,set 2 pantry design tea towels,1,2011-12-06 14:23:00,3.25,17841,United Kingdom,3.25,1
298625,410269,572098,23377,2011,10,4,15,pack of 12 dolly girl tissues,24,2011-10-20 15:38:00,0.39,15117,United Kingdom,9.36,0
49904,81041,543107,22858,2011,2,4,12,easter tin keepsake,6,2011-02-03 12:27:00,1.65,13800,United Kingdom,9.90,0
325903,443435,574700,23013,2011,11,7,13,glass apothecary bottle tonic,1,2011-11-06 13:53:00,3.95,16033,United Kingdom,3.95,1
171215,243305,558442,21366,2011,6,3,13,mirrored wall art photo frames,1,2011-06-29 13:10:00,4.25,15537,United Kingdom,4.25,0
94606,142192,548558,21992,2011,4,5,10,vintage paisley stationery set,6,2011-04-01 10:05:00,2.95,13626,United Kingdom,17.70,0
348718,473258,576787,21930,2011,11,3,13,jumbo storage bag skulls,20,2011-11-16 13:54:00,2.08,13815,Germany,41.60,0
292317,402188,571475,21908,2011,10,1,14,chocolate this way metal sign,1,2011-10-17 14:42:00,2.10,15033,United Kingdom,2.10,0
24128,37600,539471,72127,2010,12,7,14,columbian candle round,1,2010-12-19 14:16:00,1.25,17358,United Kingdom,1.25,0
351921,477663,577068,M,2011,11,4,14,manual,30,2011-11-17 14:50:00,0.30,15563,United Kingdom,9.00,0
4210,6379,536938,21931,2010,12,5,12,jumbo storage bag suki,20,2010-12-03 12:05:00,1.95,14680,United Kingdom,39.00,1
21261,32173,539044,21843,2010,12,3,15,red retrospot cake stand,1,2010-12-15 15:47:00,10.95,15727,United Kingdom,10.95,0
135298,196303,553835,22474,2011,5,4,11,spaceboy tv dinner tray,3,2011-05-19 11:50:00,4.95,13529,United Kingdom,14.85,0

In [13]:
preff_list = agg_custom.loc[(agg_custom['amount_spent'] < np.quantile(agg_custom['amount_spent'], 0.95)) & (agg_custom['amount_spent'] >= np.quantile(agg_custom['amount_spent'], 0.75))]

In [14]:
preff_list[:5]

            amount_spent
CustomerID
12347            4310.00
12348            1797.24
12349            1757.55
12352            2506.04
12356            2811.43

In [15]:
orders["Prefered"] = np.where(orders["CustomerID"].isin(preff_list.index), 1, 0)

In [16]:
orders.sort_values('amount_spent', ascending=False)

,Unnamed: 0,InvoiceNo,StockCode,year,month,day,hour,Description,Quantity,InvoiceDate,UnitPrice,CustomerID,Country,amount_spent,VIP,Prefered
397451,540421,581483,23843,2011,12,5,9,"paper craft , little birdie",80995,2011-12-09 09:15:00,2.08,16446,United Kingdom,168469.60,1,0
37126,61619,541431,23166,2011,1,2,10,medium ceramic top storage jar,74215,2011-01-18 10:01:00,1.04,12346,United Kingdom,77183.60,1,0
155418,222680,556444,22502,2011,6,5,15,picnic basket wicker 60 pieces,60,2011-06-10 15:28:00,649.50,15098,United Kingdom,38970.00,1,0
118352,173382,551697,POST,2011,5,2,13,postage,1,2011-05-03 13:46:00,8142.75,16029,United Kingdom,8142.75,1,0
248706,348325,567423,23243,2011,9,2,11,set of tea coffee sugar tins pantry,1412,2011-09-20 11:05:00,5.06,17450,United Kingdom,7144.72,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334242,454463,575579,22437,2011,11,4,11,set of 9 black skull balloons,20,2011-11-10 11:49:00,0.00,13081,United Kingdom,0.00,1,0
25379,40089,539722,22423,2010,12,2,13,regency cakestand 3 tier,10,2010-12-21 13:45:00,0.00,14911,EIRE,0.00,1,0
273926,379913,569716,22778,2011,10,4,8,glass cloche small,2,2011-10-06 08:17:00,0.00,15804,United Kingdom,0.00,0,1
353097,479546,577168,M,2011,11,5,10,manual,1,2011-11-18 10:42:00,0.00,12603,Germany,0.00,0,0
223931,314745,564651,23270,2011,8,5,14,set of 2 ceramic painted hearts,96,2011-08-26 14:19:00,0.00,14646,Netherlands,0.00,1,0

Now we'll leave it to you to solve Q2 & Q3, which you can leverage from your solution for Q1:

## Q2: How to identify which country has the most VIP Customers?

In [17]:
# your code here
agg_count = orders.groupby('Country').sum()[['VIP']]

In [18]:
agg_count.sort_values(by=['VIP'], ascending=False)[:1]

                  VIP
Country
United Kingdom  84185

## Q3: How to identify which country has the most VIP+Preferred Customers combined?

In [19]:
# your code here
agg_count = orders.groupby('Country').sum()[['VIP', 'Prefered']]

In [20]:
agg_count['Total'] = agg_count["Prefered"] + agg_count["VIP"]
agg_count.sort_values(by=['Total'], ascending=False)[:1]

                  VIP  Prefered   Total
Country
United Kingdom  84185    137450  221635