## Challenge 2: Sets

There are a lot to learn about Python Sets and the information presented in the lesson is limited due to its length. To learn Python Sets in depth you are strongly encouraged to review the W3Schools tutorial on [Python Sets Examples and Methods](https://www.w3schools.com/python/python_sets.asp) before you work on this lab. Some difficult questions in this lab have their solutions in the W3Schools tutorial.

#### First, import the Python `random` library.

In [6]:
import random

#### In the cell below, create a list named `sample_list_1` with 80 random values. 

Requirements:

* Each value is an integer falling between 0 and 100.
* Each value in the list is unique.

Print `sample_list_1` to review its values

*Hint: use `random.sample` ([reference](https://docs.python.org/3/library/random.html#random.sample)).*

In [7]:
# Your code here
sample_list_1 = random.sample(range(100), k = 80)

print(sample_list_1)

[88, 86, 91, 30, 12, 13, 71, 65, 73, 4, 99, 14, 31, 64, 90, 77, 57, 35, 79, 6, 81, 63, 94, 93, 60, 7, 27, 22, 97, 43, 80, 83, 36, 59, 68, 9, 20, 66, 98, 61, 49, 17, 18, 51, 48, 75, 69, 74, 70, 11, 10, 72, 45, 56, 55, 44, 78, 34, 62, 32, 0, 16, 2, 47, 50, 24, 89, 38, 3, 8, 46, 39, 58, 76, 82, 29, 67, 19, 96, 33]

#### Convert `sample_list_1` to a set called `set1`. Print the length of the set. Is its length still 80?

In [8]:
# Your code here
set1 = set(sample_list_1)
len(set1)

print(len(set1))

80

#### Create another list named `sample_list_2` with 80 random values.

Requirements:

* Each value is an integer falling between 0 and 100.
* The values in the list don't have to be unique.

*Hint: Use a FOR loop.*

In [9]:
# Your code here

sample_list_2 = []
                      
for i in range(80):
    sample_list_2.append(random.randint(0, 100))

print(sample_list_2)

[79, 93, 95, 13, 38, 13, 15, 83, 20, 36, 76, 55, 84, 39, 67, 33, 4, 32, 13, 73, 100, 11, 65, 63, 80, 99, 99, 16, 23, 26, 17, 70, 47, 72, 4, 89, 66, 13, 5, 17, 64, 18, 66, 79, 59, 62, 41, 79, 99, 55, 14, 24, 92, 56, 27, 55, 15, 67, 29, 31, 84, 44, 77, 79, 91, 97, 17, 11, 6, 10, 19, 32, 24, 41, 19, 78, 47, 25, 4, 71]

#### Convert `sample_list_2` to a set called `set2`. Print the length of the set. Is its length still 80?

In [10]:
# Your code here
set2 = set(sample_list_2)
print(len(set2))

56

#### Identify the elements present in `set1` but not in `set2`. Assign the elements to a new set named `set3`.

In [11]:
# Your code here
set3 = set()
for i in range(100):
    if i in set1 and i not in set2:
        set3.add(i)
print(set3)
print(len(set3))

{0, 2, 3, 7, 8, 9, 12, 22, 30, 34, 35, 43, 45, 46, 48, 49, 50, 51, 57, 58, 60, 61, 68, 69, 74, 75, 81, 82, 86, 88, 90, 94, 96, 98}
34

#### Identify the elements present in `set2` but not in `set1`. Assign the elements to a new set named `set4`.

In [12]:
# Your code here
set4 = set()
for i in range(100):
    if i in set2 and i not in set1:
        set4.add(i)
print(set4)

{5, 41, 15, 84, 23, 25, 26, 92, 95}

#### Now Identify the elements shared between `set1` and `set2`. Assign the elements to a new set named `set5`.

In [13]:
# Your code here
set5 = set()
for i in range(100):
    if i in set2 and i in set1:
        set5.add(i)
print(set5)

{4, 6, 10, 11, 13, 14, 16, 17, 18, 19, 20, 24, 27, 29, 31, 32, 33, 36, 38, 39, 44, 47, 55, 56, 59, 62, 63, 64, 65, 66, 67, 70, 71, 72, 73, 76, 77, 78, 79, 80, 83, 89, 91, 93, 97, 99}

#### What is the relationship among the following values:

* len(set1)
* len(set2)
* len(set3)
* len(set4)
* len(set5)

Use a math formular to represent that relationship. Test your formular with Python code.

In [22]:
# Your code here
len(set5)*2+len(set3)+len(set4)==len(set1)+len(set2)

False

#### Create an empty set called `set6`.

In [23]:
# Your code here
set6 = set()

#### Add `set3` and `set5` to `set6` using the Python Set `update` method.

In [16]:
# Your code here
set6.update(set3)
set6.update(set5)
print(set6)

{0, 2, 3, 4, 6, 7, 8, 9, 10, 11, 12, 13, 14, 16, 17, 18, 19, 20, 22, 24, 27, 29, 30, 31, 32, 33, 34, 35, 36, 38, 39, 43, 44, 45, 46, 47, 48, 49, 50, 51, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 86, 88, 89, 90, 91, 93, 94, 96, 97, 98, 99}

#### Check if `set1` and `set6` are equal.

In [17]:
# Your code here
set1 == set6

True

#### Check if `set1` contains `set2` using the Python Set `issubset` method. Then check if `set1` contains `set3`.*

In [18]:
# Your code here
print(set2.issubset(set1))
print(set3.issubset(set1))

False
True

#### Using the Python Set `union` method, aggregate `set3`, `set4`, and `set5`. Then aggregate `set1` and `set2`. 

#### Check if the aggregated values are equal.

In [19]:
# Your code here
aggregate1 = set3.union(set4, set5)
aggregate2 = set1.union(set2)

aggregate1 == aggregate2

False

#### Using the `pop` method, remove the first element from `set1`.

In [20]:
# Your code here

#### Remove every element in the following list from `set1` if they are present in the set. Print the remaining elements.

```
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]
```

In [21]:
# Your code here
list_to_remove = [1, 9, 11, 19, 21, 29, 31, 39, 41, 49, 51, 59, 61, 69, 71, 79, 81, 89, 91, 99]

for i in list_to_remove:
    if i in set1:
        set1.remove(i)
print(set1)

{0, 2, 3, 4, 6, 7, 8, 10, 12, 13, 14, 16, 17, 18, 20, 22, 24, 27, 30, 32, 33, 34, 35, 36, 38, 43, 44, 45, 46, 47, 48, 50, 55, 56, 57, 58, 60, 62, 63, 64, 65, 66, 67, 68, 70, 72, 73, 74, 75, 76, 77, 78, 80, 82, 83, 86, 88, 90, 93, 94, 96, 97, 98}